---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  controlPlaneFailureDomains:
    - name: ${NUTANIX_FAILURE_DOMAIN_1_NAME}
    - name: ${NUTANIX_FAILURE_DOMAIN_2_NAME}
    - name: ${NUTANIX_FAILURE_DOMAIN_3_NAME}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-kcp
spec:
  replicas: 3
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
  name: ${CLUSTER_NAME}-wmd
spec:
  replicas: ${WORKER_MACHINE_COUNT=3}
  template:
    spec:
      failureDomain: ${NUTANIX_FAILURE_DOMAIN_1_NAME}
