apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
- ../base/
- ./failure-domains.yaml

patches:
- path: ./failure-domains-patch.yaml
- target:
    kind: NutanixMachineTemplate
  patch: |-
    - op: "remove"
      path: "/spec/template/spec/cluster"
    - op: "remove"
      path: "/spec/template/spec/subnet"
