# Copyright 2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nutanix-image-lookup-kustomize

resources:
  - ../base/

patches:
- path: lookup-patch.yaml
- target:
    kind: NutanixMachineTemplate
  patch: |-
    - op: "remove"
      path: "/spec/template/spec/image"
