apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: merge
  files:
  - nutanix-ccm.yaml
  name: nutanix-ccm

resources:
- ./nutanix-ccm-crs.yaml
- ./nutanix-ccm-secret.yaml
