apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: nutanix-ccm
  behavior: merge
  files:
  - nutanix-ccm.yaml

bases:
  - ./nutanix-ccm-crs.yaml
  - ./nutanix-ccm-secret.yaml
