apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nutanix-creds
  namespace: capi-nutanix-system
stringData:
  NUTANIX_ENDPOINT: "${NUTANIX_ENDPOINT}"
  NUTANIX_PORT: "9440"
  NUTANIX_USER: "${NUTANIX_USER}"
  NUTANIX_PASSWORD: "${NUTANIX_PASSWORD}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
          image: controller
          imagePullPolicy: IfNotPresent
          name: manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NUTANIX_USER
              valueFrom:
                secretKeyRef:
                  name: nutanix-creds
                  key: NUTANIX_USER
            - name: NUTANIX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nutanix-creds
                  key: NUTANIX_PASSWORD
            - name: NUTANIX_PORT
              valueFrom:
                secretKeyRef:
                  name: nutanix-creds
                  key: NUTANIX_PORT
            - name: NUTANIX_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: nutanix-creds
                  key: NUTANIX_ENDPOINT
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
