apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nutanix-endpoint
  namespace: capi-nutanix-system
data:
  prismCentral: |-
    {
      "address": "${NUTANIX_ENDPOINT}",
      "port": ${NUTANIX_PORT=9440},
      "insecure": ${NUTANIX_INSECURE=false},
      "credentialRef": {
        "kind": "secret",
        "name": "capx-nutanix-creds"
      }
    }
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nutanix-creds
  namespace: capi-nutanix-system
stringData:
  credentials: |
    [
      {
        "type": "basic_auth", 
        "data": { 
          "prismCentral":{
            "username": "${NUTANIX_USER}",
            "password": "${NUTANIX_PASSWORD}"
          },
          "prismElements": null
        }
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      # securityContext:
      #   runAsNonRoot: true
      containers:
        - args:
            - --leader-elect
          image: controller
          imagePullPolicy: IfNotPresent
          name: manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: endpoint
              mountPath: "/etc/nutanix/config"
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 40m
              memory: 60Mi
            requests:
              cpu: 30m
              memory: 50Mi
      volumes:
        - name: endpoint
          configMap:
            name: nutanix-endpoint
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
