apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineHealthCheck
metadata:
  name: "${CLUSTER_NAME}-mhc"
spec:
  clusterName: "${CLUSTER_NAME}"
  remediation:
    triggerIf:
      unhealthyLessThanOrEqualTo: 40%
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
  checks:
    nodeStartupTimeoutSeconds: 600
    unhealthyNodeConditions:
      - type: Ready
        status: "False"
        timeoutSeconds: 300
      - type: Ready
        status: Unknown
        timeoutSeconds: 300
      - type: MemoryPressure
        status: "True"
        timeoutSeconds: 300
      - type: DiskPressure
        status: "True"
        timeoutSeconds: 300
      - type: PIDPressure
        status: "True"
        timeoutSeconds: 300
      - type: NetworkUnavailable
        status: "True"
        timeoutSeconds: 300
