apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: "${CLUSTER_NAME}-mhc"
spec:
  clusterName: "${CLUSTER_NAME}"
  maxUnhealthy: 40%
  nodeStartupTimeout: 10m0s
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: "${CLUSTER_NAME}"
  unhealthyConditions:
    - type: Ready
      status: "False"
      timeout: 5m0s
    - type: Ready
      status: Unknown
      timeout: 5m0s
    - type: MemoryPressure
      status: "True"
      timeout: 5m0s
    - type: DiskPressure
      status: "True"
      timeout: 5m0s
    - type: PIDPressure
      status: "True"
      timeout: 5m0s
    - type: NetworkUnavailable
      status: "True"
      timeout: 5m0s
