# permissions for end users to edit nutanixvmantiaffinitypolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nutanixvmantiaffinitypolicy-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - nutanixvmantiaffinitypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - nutanixvmantiaffinitypolicies/status
  verbs:
  - get