apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../topology

patches:
- target:
    kind: Secret
    name: '\$\{CLUSTER_NAME\}-pc-creds'
  patch: |-
    - op: replace
      path: /stringData/credentials
      value: |
        [
          {
            "type": "api_key",
            "data": {
              "prismCentral":{
                "apiKey": "${NUTANIX_API_KEY}"
              },
              "prismElements": null
            }
          }
        ]
