apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: merge
  files:
  - nutanix-ccm.yaml
  name: nutanix-ccm


resources:
- ./cm.yaml
- ./cluster-with-topology.yaml
- ./secret.yaml
- ./nutanix-ccm-secret.yaml
- ./nutanix-ccm-crs.yaml
patches:
- path: ./ccm-patch.yaml
