---
apiVersion: v1
kind: Secret
metadata:
  name: "${CLUSTER_NAME}-pc-creds"
stringData:
  credentials: |
    [
      {
        "type": "${NUTANIX_CREDENTIALS_TYPE}",
        "data": {
          "prismCentral":{
            "username": "${NUTANIX_USER}",
            "password": "${NUTANIX_PASSWORD}",
            "apiKey": "${NUTANIX_API_KEY}"
          },
          "prismElements": null
        }
      }
    ]
