apiVersion: v1
binaryData:
  ca.crt: ${NUTANIX_ADDITIONAL_TRUST_BUNDLE=""}
kind: ConfigMap
metadata:
  name: ${CLUSTER_NAME}-pc-trusted-ca-bundle
---
apiVersion: v1
data:
  nutanix-ccm.yaml: |
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${CLUSTER_NAME}-pc-trusted-ca-bundle
      namespace: kube-system
    binaryData:
      ca.crt: ${NUTANIX_ADDITIONAL_TRUST_BUNDLE=""}
    ---
    # Source: nutanix-cloud-provider/templates/rbac.yaml
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: cloud-controller-manager
      namespace: kube-system
    ---
    # Source: nutanix-cloud-provider/templates/cm.yaml
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: nutanix-config
      namespace: kube-system
    data:
      nutanix_config.json: |-
        {
          "prismCentral": {
            "address": "${NUTANIX_ENDPOINT}",
            "port": ${NUTANIX_PORT=9440},
            "insecure": ${NUTANIX_INSECURE=false},
            "credentialRef": {
              "kind": "secret",
              "name": "nutanix-creds",
              "namespace": "kube-system"
            },
            "additionalTrustBundle": {
              "kind": "ConfigMap",
              "name": "nutanix-ccm-pc-trusted-ca-bundle",
              "namespace": "kube-system"
            }
          },
          "enableCustomLabeling": ${CCM_CUSTOM_LABEL=false},
          "topologyDiscovery": {
            "type": "Prism"
          }
        }
    ---
    # Source: nutanix-cloud-provider/templates/rbac.yaml
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      annotations:
        rbac.authorization.kubernetes.io/autoupdate: "true"
      name: system:cloud-controller-manager
    rules:
      - apiGroups:
          - ""
        resources:
          - secrets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ""
        resources:
          - events
        verbs:
          - create
          - patch
          - update
      - apiGroups:
          - ""
        resources:
          - nodes
        verbs:
          - "*"
      - apiGroups:
          - ""
        resources:
          - nodes/status
        verbs:
          - patch
      - apiGroups:
          - ""
        resources:
          - serviceaccounts
        verbs:
          - create
      - apiGroups:
          - ""
        resources:
          - endpoints
        verbs:
          - create
          - get
          - list
          - watch
          - update
      - apiGroups:
          - coordination.k8s.io
        resources:
          - leases
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
    ---
    # Source: nutanix-cloud-provider/templates/rbac.yaml
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: system:cloud-controller-manager
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:cloud-controller-manager
    subjects:
      - kind: ServiceAccount
        name: cloud-controller-manager
        namespace: kube-system
    ---
    # Source: nutanix-cloud-provider/templates/cloud-provider-nutanix-deployment.yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        k8s-app: nutanix-cloud-controller-manager
      name: nutanix-cloud-controller-manager
      namespace: kube-system
    spec:
      replicas: 1
      selector:
        matchLabels:
          k8s-app: nutanix-cloud-controller-manager
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            k8s-app: nutanix-cloud-controller-manager
        spec:
          hostNetwork: true
          priorityClassName: system-cluster-critical
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          serviceAccountName: cloud-controller-manager
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    k8s-app: nutanix-cloud-controller-manager
                topologyKey: kubernetes.io/hostname
          dnsPolicy: Default
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
              operator: Exists
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
              operator: Exists
            - effect: NoExecute
              key: node.kubernetes.io/unreachable
              operator: Exists
              tolerationSeconds: 120
            - effect: NoExecute
              key: node.kubernetes.io/not-ready
              operator: Exists
              tolerationSeconds: 120
            - effect: NoSchedule
              key: node.cloudprovider.kubernetes.io/uninitialized
              operator: Exists
            - effect: NoSchedule
              key: node.kubernetes.io/not-ready
              operator: Exists
          containers:
            - image: "${CCM_REPO=ghcr.io/nutanix-cloud-native/cloud-provider-nutanix/controller}:${CCM_TAG=v0.3.2}"
              imagePullPolicy: IfNotPresent
              name: nutanix-cloud-controller-manager
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              args:
                - "--leader-elect=true"
                - "--cloud-config=/etc/cloud/nutanix_config.json"
              resources:
                requests:
                  cpu: 100m
                  memory: 50Mi
              volumeMounts:
                - mountPath: /etc/cloud
                  name: nutanix-config-volume
                  readOnly: true
          volumes:
            - name: nutanix-config-volume
              configMap:
                name: nutanix-config
kind: ConfigMap
metadata:
  name: nutanix-ccm
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CLUSTER_NAME}-pc-creds
stringData:
  credentials: |
    [
      {
        "type": "basic_auth",
        "data": {
          "prismCentral":{
            "username": "${NUTANIX_USER}",
            "password": "${NUTANIX_PASSWORD}"
          }
        }
      }
    ]
---
apiVersion: v1
kind: Secret
metadata:
  name: nutanix-ccm-secret
stringData:
  nutanix-ccm-secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: nutanix-creds
      namespace: kube-system
    stringData:
      credentials: |
        [
          {
            "type": "basic_auth",
            "data": {
              "prismCentral":{
                "username": "${NUTANIX_USER}",
                "password": "${NUTANIX_PASSWORD}"
              },
              "prismElements": null
            }
          }
        ]
type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: nutanix-ccm-crs
spec:
  clusterSelector:
    matchLabels:
      ccm: nutanix
  resources:
  - kind: ConfigMap
    name: nutanix-ccm
  - kind: Secret
    name: nutanix-ccm-secret
  - kind: ConfigMap
    name: nutanix-ccm-pc-trusted-ca-bundle
  strategy: ApplyOnce
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    ccm: nutanix
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.20.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 172.19.0.0/16
  topology:
    class: nutanix-quick-start
    controlPlane:
      metadata: {}
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
    - name: sshKey
      value: ${NUTANIX_SSH_AUTHORIZED_KEY}
    - name: controlPlaneEndpoint
      value:
        IP: ${CONTROL_PLANE_ENDPOINT_IP}
        port: ${CONTROL_PLANE_ENDPOINT_PORT=6443}
    - name: prismCentralEndpoint
      value:
        additionalTrustBundle: ${CLUSTER_NAME}-pc-trusted-ca-bundle
        address: ${NUTANIX_ENDPOINT}
        credentialSecret: ${CLUSTER_NAME}-pc-creds
        insecure: ${NUTANIX_INSECURE=false}
        port: ${NUTANIX_PORT=9440}
    - name: controlPlaneMachineDetails
      value:
        bootType: ${NUTANIX_MACHINE_BOOT_TYPE=legacy}
        clusterName: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
        imageName: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
        memorySize: ${NUTANIX_MACHINE_MEMORY_SIZE=4Gi}
        subnetName: ${NUTANIX_SUBNET_NAME}
        systemDiskSize: ${NUTANIX_SYSTEMDISK_SIZE=40Gi}
        vcpuSockets: ${NUTANIX_MACHINE_VCPU_SOCKET=2}
        vcpusPerSocket: ${NUTANIX_MACHINE_VCPU_PER_SOCKET=1}
    - name: workerMachineDetails
      value:
        bootType: ${NUTANIX_MACHINE_BOOT_TYPE=legacy}
        clusterName: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
        imageName: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
        memorySize: ${NUTANIX_MACHINE_MEMORY_SIZE=4Gi}
        subnetName: ${NUTANIX_SUBNET_NAME}
        systemDiskSize: ${NUTANIX_SYSTEMDISK_SIZE=40Gi}
        vcpuSockets: ${NUTANIX_MACHINE_VCPU_SOCKET=2}
        vcpusPerSocket: ${NUTANIX_MACHINE_VCPU_PER_SOCKET=1}
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
      - class: nutanix-quick-start-worker
        metadata: {}
        name: md-0
        replicas: ${WORKER_MACHINE_COUNT}
