apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../ccm
  - ./cm.yaml
  - ./secret.yaml
  - ./nct.yaml
  - ./clusterclass.yaml
  - ./nmt-cp.yaml
  - ./nmt-md.yaml
  - ./kcpt.yaml
  - ./kct.yaml
