apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixClusterTemplate
metadata:
  name: nutanix-quick-start-nct
spec:
  template:
    spec:
      controlPlaneEndpoint:
        host: PLACEHOLDER
        port: 6443
      prismCentral:
        address: PLACEHOLDER
        port: 9440
        credentialRef:
          name: PLACEHOLDER
          kind: Secret
          namespace: default
      failureDomains: []
