# Alpine is a very small base package.  Consider ubuntu:20.04 if you want something more full featured.
FROM docker.dyn.ntnxdpro.com/ntnx-general-docker/alpine:latest

# Please add your own instructions below to build your docker image.
CMD echo 'Hello, World'
