apiVersion: v1
kind: Secret
metadata:
  name: nutanix-csi-secret
type: addons.cluster.x-k8s.io/resource-set
stringData:
  nutanix-csi-secret.yaml: |
    apiVersion: v1
    stringData:
      key: ${NUTANIX_ENDPOINT}:${NUTANIX_PORT}:${NUTANIX_USER}:${NUTANIX_PASSWORD}
    kind: Secret
    metadata:
      name: nutanix-csi-credentials
      namespace: ntnx-system
    type: Opaque
