apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ template "chart.name" . }}-admission
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: admission
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
