apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../default

patches:
- target:
    kind: Secret
    name: 'nutanix-creds'
    namespace: capi-nutanix-system
  patch: |-
    - op: replace
      path: /stringData/credentials
      value: |
        [
          {
            "type": "api_key",
            "data": {
              "prismCentral":{
                "apiKey": "${NUTANIX_API_KEY}"
              },
              "prismElements": null
            }
          }
        ]
