// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: AntiAffinityPolicies)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/anti_affinity_policies.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged AntiAffinityPolicies
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockAntiAffinityPolicies is a mock of AntiAffinityPolicies interface.
type MockAntiAffinityPolicies[AntiAffinityPolicy any] struct {
	ctrl     *gomock.Controller
	recorder *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]
	isgomock struct{}
}

// MockAntiAffinityPoliciesMockRecorder is the mock recorder for MockAntiAffinityPolicies.
type MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy any] struct {
	mock *MockAntiAffinityPolicies[AntiAffinityPolicy]
}

// NewMockAntiAffinityPolicies creates a new mock instance.
func NewMockAntiAffinityPolicies[AntiAffinityPolicy any](ctrl *gomock.Controller) *MockAntiAffinityPolicies[AntiAffinityPolicy] {
	mock := &MockAntiAffinityPolicies[AntiAffinityPolicy]{ctrl: ctrl}
	mock.recorder = &MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) EXPECT() *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy] {
	return m.recorder
}

// Create mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) Create(ctx context.Context, entity *AntiAffinityPolicy) (*AntiAffinityPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*AntiAffinityPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).Create), ctx, entity)
}

// CreateAsync mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) CreateAsync(ctx context.Context, entity *AntiAffinityPolicy) (converged.Operation[AntiAffinityPolicy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsync", ctx, entity)
	ret0, _ := ret[0].(converged.Operation[AntiAffinityPolicy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAsync indicates an expected call of CreateAsync.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) CreateAsync(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsync", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).CreateAsync), ctx, entity)
}

// Delete mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) Delete(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) Delete(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).Delete), ctx, uuid)
}

// DeleteAsync mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) DeleteAsync(ctx context.Context, uuid string) (converged.Operation[converged.NoEntity], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsync", ctx, uuid)
	ret0, _ := ret[0].(converged.Operation[converged.NoEntity])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAsync indicates an expected call of DeleteAsync.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) DeleteAsync(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsync", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).DeleteAsync), ctx, uuid)
}

// Get mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) Get(ctx context.Context, uuid string) (*AntiAffinityPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*AntiAffinityPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).Get), ctx, uuid)
}

// List mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) List(ctx context.Context, opts ...converged.ODataOption) ([]AntiAffinityPolicy, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]AntiAffinityPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).List), varargs...)
}

// NewIterator mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[AntiAffinityPolicy] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[AntiAffinityPolicy])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).NewIterator), varargs...)
}

// Update mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) Update(ctx context.Context, uuid string, entity *AntiAffinityPolicy) (*AntiAffinityPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, uuid, entity)
	ret0, _ := ret[0].(*AntiAffinityPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) Update(ctx, uuid, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).Update), ctx, uuid, entity)
}

// UpdateAsync mocks base method.
func (m *MockAntiAffinityPolicies[AntiAffinityPolicy]) UpdateAsync(ctx context.Context, uuid string, entity *AntiAffinityPolicy) (converged.Operation[AntiAffinityPolicy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAsync", ctx, uuid, entity)
	ret0, _ := ret[0].(converged.Operation[AntiAffinityPolicy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAsync indicates an expected call of UpdateAsync.
func (mr *MockAntiAffinityPoliciesMockRecorder[AntiAffinityPolicy]) UpdateAsync(ctx, uuid, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAsync", reflect.TypeOf((*MockAntiAffinityPolicies[AntiAffinityPolicy])(nil).UpdateAsync), ctx, uuid, entity)
}
