// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: DomainManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/domain_manager.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged DomainManager
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockDomainManager is a mock of DomainManager interface.
type MockDomainManager[DomainManagerEntity any] struct {
	ctrl     *gomock.Controller
	recorder *MockDomainManagerMockRecorder[DomainManagerEntity]
	isgomock struct{}
}

// MockDomainManagerMockRecorder is the mock recorder for MockDomainManager.
type MockDomainManagerMockRecorder[DomainManagerEntity any] struct {
	mock *MockDomainManager[DomainManagerEntity]
}

// NewMockDomainManager creates a new mock instance.
func NewMockDomainManager[DomainManagerEntity any](ctrl *gomock.Controller) *MockDomainManager[DomainManagerEntity] {
	mock := &MockDomainManager[DomainManagerEntity]{ctrl: ctrl}
	mock.recorder = &MockDomainManagerMockRecorder[DomainManagerEntity]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainManager[DomainManagerEntity]) EXPECT() *MockDomainManagerMockRecorder[DomainManagerEntity] {
	return m.recorder
}

// Get mocks base method.
func (m *MockDomainManager[DomainManagerEntity]) Get(ctx context.Context, uuid string) (*DomainManagerEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*DomainManagerEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDomainManagerMockRecorder[DomainManagerEntity]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDomainManager[DomainManagerEntity])(nil).Get), ctx, uuid)
}

// GetPrismCentralVersion mocks base method.
func (m *MockDomainManager[DomainManagerEntity]) GetPrismCentralVersion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrismCentralVersion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrismCentralVersion indicates an expected call of GetPrismCentralVersion.
func (mr *MockDomainManagerMockRecorder[DomainManagerEntity]) GetPrismCentralVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrismCentralVersion", reflect.TypeOf((*MockDomainManager[DomainManagerEntity])(nil).GetPrismCentralVersion), ctx)
}

// List mocks base method.
func (m *MockDomainManager[DomainManagerEntity]) List(ctx context.Context, opts ...converged.ODataOption) ([]DomainManagerEntity, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]DomainManagerEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDomainManagerMockRecorder[DomainManagerEntity]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDomainManager[DomainManagerEntity])(nil).List), varargs...)
}

// NewIterator mocks base method.
func (m *MockDomainManager[DomainManagerEntity]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[DomainManagerEntity] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[DomainManagerEntity])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockDomainManagerMockRecorder[DomainManagerEntity]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockDomainManager[DomainManagerEntity])(nil).NewIterator), varargs...)
}
