// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: Ovas)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/ovas.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged Ovas
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockOvas is a mock of Ovas interface.
type MockOvas[Ova any, FileDetail any] struct {
	ctrl     *gomock.Controller
	recorder *MockOvasMockRecorder[Ova, FileDetail]
	isgomock struct{}
}

// MockOvasMockRecorder is the mock recorder for MockOvas.
type MockOvasMockRecorder[Ova any, FileDetail any] struct {
	mock *MockOvas[Ova, FileDetail]
}

// NewMockOvas creates a new mock instance.
func NewMockOvas[Ova any, FileDetail any](ctrl *gomock.Controller) *MockOvas[Ova, FileDetail] {
	mock := &MockOvas[Ova, FileDetail]{ctrl: ctrl}
	mock.recorder = &MockOvasMockRecorder[Ova, FileDetail]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOvas[Ova, FileDetail]) EXPECT() *MockOvasMockRecorder[Ova, FileDetail] {
	return m.recorder
}

// Create mocks base method.
func (m *MockOvas[Ova, FileDetail]) Create(ctx context.Context, entity *Ova) (*Ova, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*Ova)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOvasMockRecorder[Ova, FileDetail]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOvas[Ova, FileDetail])(nil).Create), ctx, entity)
}

// Get mocks base method.
func (m *MockOvas[Ova, FileDetail]) Get(ctx context.Context, uuid string) (*Ova, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*Ova)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOvasMockRecorder[Ova, FileDetail]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOvas[Ova, FileDetail])(nil).Get), ctx, uuid)
}

// GetFile mocks base method.
func (m *MockOvas[Ova, FileDetail]) GetFile(ctx context.Context, uuid string) (*FileDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, uuid)
	ret0, _ := ret[0].(*FileDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockOvasMockRecorder[Ova, FileDetail]) GetFile(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockOvas[Ova, FileDetail])(nil).GetFile), ctx, uuid)
}

// List mocks base method.
func (m *MockOvas[Ova, FileDetail]) List(ctx context.Context, opts ...converged.ODataOption) ([]Ova, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]Ova)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOvasMockRecorder[Ova, FileDetail]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOvas[Ova, FileDetail])(nil).List), varargs...)
}

// NewIterator mocks base method.
func (m *MockOvas[Ova, FileDetail]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[Ova] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[Ova])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockOvasMockRecorder[Ova, FileDetail]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockOvas[Ova, FileDetail])(nil).NewIterator), varargs...)
}
