// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: Projects)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/projects.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged Projects
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockProjects is a mock of Projects interface.
type MockProjects[Project any] struct {
	ctrl     *gomock.Controller
	recorder *MockProjectsMockRecorder[Project]
	isgomock struct{}
}

// MockProjectsMockRecorder is the mock recorder for MockProjects.
type MockProjectsMockRecorder[Project any] struct {
	mock *MockProjects[Project]
}

// NewMockProjects creates a new mock instance.
func NewMockProjects[Project any](ctrl *gomock.Controller) *MockProjects[Project] {
	mock := &MockProjects[Project]{ctrl: ctrl}
	mock.recorder = &MockProjectsMockRecorder[Project]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjects[Project]) EXPECT() *MockProjectsMockRecorder[Project] {
	return m.recorder
}

// Get mocks base method.
func (m *MockProjects[Project]) Get(ctx context.Context, uuid string) (*Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectsMockRecorder[Project]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjects[Project])(nil).Get), ctx, uuid)
}

// GetByName mocks base method.
func (m *MockProjects[Project]) GetByName(ctx context.Context, name string) (*Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockProjectsMockRecorder[Project]) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockProjects[Project])(nil).GetByName), ctx, name)
}

// GetDefaultProject mocks base method.
func (m *MockProjects[Project]) GetDefaultProject(ctx context.Context) (*Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultProject", ctx)
	ret0, _ := ret[0].(*Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultProject indicates an expected call of GetDefaultProject.
func (mr *MockProjectsMockRecorder[Project]) GetDefaultProject(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultProject", reflect.TypeOf((*MockProjects[Project])(nil).GetDefaultProject), ctx)
}

// List mocks base method.
func (m *MockProjects[Project]) List(ctx context.Context, opts ...converged.ODataOption) ([]Project, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectsMockRecorder[Project]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjects[Project])(nil).List), varargs...)
}

// NewIterator mocks base method.
func (m *MockProjects[Project]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[Project] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[Project])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockProjectsMockRecorder[Project]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockProjects[Project])(nil).NewIterator), varargs...)
}
