// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: ProtectionPolicies)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/protection_policies.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged ProtectionPolicies
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockProtectionPolicies is a mock of ProtectionPolicies interface.
type MockProtectionPolicies[ProtectionPolicy any] struct {
	ctrl     *gomock.Controller
	recorder *MockProtectionPoliciesMockRecorder[ProtectionPolicy]
	isgomock struct{}
}

// MockProtectionPoliciesMockRecorder is the mock recorder for MockProtectionPolicies.
type MockProtectionPoliciesMockRecorder[ProtectionPolicy any] struct {
	mock *MockProtectionPolicies[ProtectionPolicy]
}

// NewMockProtectionPolicies creates a new mock instance.
func NewMockProtectionPolicies[ProtectionPolicy any](ctrl *gomock.Controller) *MockProtectionPolicies[ProtectionPolicy] {
	mock := &MockProtectionPolicies[ProtectionPolicy]{ctrl: ctrl}
	mock.recorder = &MockProtectionPoliciesMockRecorder[ProtectionPolicy]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtectionPolicies[ProtectionPolicy]) EXPECT() *MockProtectionPoliciesMockRecorder[ProtectionPolicy] {
	return m.recorder
}

// Create mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) Create(ctx context.Context, entity *ProtectionPolicy) (*ProtectionPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*ProtectionPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).Create), ctx, entity)
}

// CreateAsync mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) CreateAsync(ctx context.Context, entity *ProtectionPolicy) (converged.Operation[ProtectionPolicy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsync", ctx, entity)
	ret0, _ := ret[0].(converged.Operation[ProtectionPolicy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAsync indicates an expected call of CreateAsync.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) CreateAsync(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsync", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).CreateAsync), ctx, entity)
}

// Delete mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) Delete(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) Delete(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).Delete), ctx, uuid)
}

// DeleteAsync mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) DeleteAsync(ctx context.Context, uuid string) (converged.Operation[converged.NoEntity], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsync", ctx, uuid)
	ret0, _ := ret[0].(converged.Operation[converged.NoEntity])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAsync indicates an expected call of DeleteAsync.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) DeleteAsync(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsync", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).DeleteAsync), ctx, uuid)
}

// Get mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) Get(ctx context.Context, uuid string) (*ProtectionPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*ProtectionPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).Get), ctx, uuid)
}

// List mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) List(ctx context.Context, opts ...converged.ODataOption) ([]ProtectionPolicy, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]ProtectionPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).List), varargs...)
}

// NewIterator mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[ProtectionPolicy] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[ProtectionPolicy])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).NewIterator), varargs...)
}

// Update mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) Update(ctx context.Context, uuid string, entity *ProtectionPolicy) (*ProtectionPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, uuid, entity)
	ret0, _ := ret[0].(*ProtectionPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) Update(ctx, uuid, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).Update), ctx, uuid, entity)
}

// UpdateAsync mocks base method.
func (m *MockProtectionPolicies[ProtectionPolicy]) UpdateAsync(ctx context.Context, uuid string, entity *ProtectionPolicy) (converged.Operation[ProtectionPolicy], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAsync", ctx, uuid, entity)
	ret0, _ := ret[0].(converged.Operation[ProtectionPolicy])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAsync indicates an expected call of UpdateAsync.
func (mr *MockProtectionPoliciesMockRecorder[ProtectionPolicy]) UpdateAsync(ctx, uuid, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAsync", reflect.TypeOf((*MockProtectionPolicies[ProtectionPolicy])(nil).UpdateAsync), ctx, uuid, entity)
}
