// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: RecoveryPlans)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/recovery_plans.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged RecoveryPlans
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockRecoveryPlans is a mock of RecoveryPlans interface.
type MockRecoveryPlans[RecoveryPlan any] struct {
	ctrl     *gomock.Controller
	recorder *MockRecoveryPlansMockRecorder[RecoveryPlan]
	isgomock struct{}
}

// MockRecoveryPlansMockRecorder is the mock recorder for MockRecoveryPlans.
type MockRecoveryPlansMockRecorder[RecoveryPlan any] struct {
	mock *MockRecoveryPlans[RecoveryPlan]
}

// NewMockRecoveryPlans creates a new mock instance.
func NewMockRecoveryPlans[RecoveryPlan any](ctrl *gomock.Controller) *MockRecoveryPlans[RecoveryPlan] {
	mock := &MockRecoveryPlans[RecoveryPlan]{ctrl: ctrl}
	mock.recorder = &MockRecoveryPlansMockRecorder[RecoveryPlan]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecoveryPlans[RecoveryPlan]) EXPECT() *MockRecoveryPlansMockRecorder[RecoveryPlan] {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) Create(ctx context.Context, entity *RecoveryPlan) (*RecoveryPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*RecoveryPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).Create), ctx, entity)
}

// CreateAsync mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) CreateAsync(ctx context.Context, entity *RecoveryPlan) (converged.Operation[RecoveryPlan], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAsync", ctx, entity)
	ret0, _ := ret[0].(converged.Operation[RecoveryPlan])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAsync indicates an expected call of CreateAsync.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) CreateAsync(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsync", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).CreateAsync), ctx, entity)
}

// Delete mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) Delete(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) Delete(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).Delete), ctx, uuid)
}

// DeleteAsync mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) DeleteAsync(ctx context.Context, uuid string) (converged.Operation[converged.NoEntity], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsync", ctx, uuid)
	ret0, _ := ret[0].(converged.Operation[converged.NoEntity])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAsync indicates an expected call of DeleteAsync.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) DeleteAsync(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsync", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).DeleteAsync), ctx, uuid)
}

// Get mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) Get(ctx context.Context, uuid string) (*RecoveryPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*RecoveryPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).Get), ctx, uuid)
}

// List mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) List(ctx context.Context, opts ...converged.ODataOption) ([]RecoveryPlan, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]RecoveryPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).List), varargs...)
}

// NewIterator mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[RecoveryPlan] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[RecoveryPlan])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).NewIterator), varargs...)
}

// Update mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) Update(ctx context.Context, uuid string, entity *RecoveryPlan) (*RecoveryPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, uuid, entity)
	ret0, _ := ret[0].(*RecoveryPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) Update(ctx, uuid, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).Update), ctx, uuid, entity)
}

// UpdateAsync mocks base method.
func (m *MockRecoveryPlans[RecoveryPlan]) UpdateAsync(ctx context.Context, uuid string, entity *RecoveryPlan) (converged.Operation[RecoveryPlan], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAsync", ctx, uuid, entity)
	ret0, _ := ret[0].(converged.Operation[RecoveryPlan])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAsync indicates an expected call of UpdateAsync.
func (mr *MockRecoveryPlansMockRecorder[RecoveryPlan]) UpdateAsync(ctx, uuid, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAsync", reflect.TypeOf((*MockRecoveryPlans[RecoveryPlan])(nil).UpdateAsync), ctx, uuid, entity)
}
