// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: ResourceGroups)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/resource_groups.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged ResourceGroups
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockResourceGroups is a mock of ResourceGroups interface.
type MockResourceGroups[ResourceGroup any] struct {
	ctrl     *gomock.Controller
	recorder *MockResourceGroupsMockRecorder[ResourceGroup]
	isgomock struct{}
}

// MockResourceGroupsMockRecorder is the mock recorder for MockResourceGroups.
type MockResourceGroupsMockRecorder[ResourceGroup any] struct {
	mock *MockResourceGroups[ResourceGroup]
}

// NewMockResourceGroups creates a new mock instance.
func NewMockResourceGroups[ResourceGroup any](ctrl *gomock.Controller) *MockResourceGroups[ResourceGroup] {
	mock := &MockResourceGroups[ResourceGroup]{ctrl: ctrl}
	mock.recorder = &MockResourceGroupsMockRecorder[ResourceGroup]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceGroups[ResourceGroup]) EXPECT() *MockResourceGroupsMockRecorder[ResourceGroup] {
	return m.recorder
}

// Get mocks base method.
func (m *MockResourceGroups[ResourceGroup]) Get(ctx context.Context, uuid string) (*ResourceGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*ResourceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockResourceGroupsMockRecorder[ResourceGroup]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResourceGroups[ResourceGroup])(nil).Get), ctx, uuid)
}

// List mocks base method.
func (m *MockResourceGroups[ResourceGroup]) List(ctx context.Context, opts ...converged.ODataOption) ([]ResourceGroup, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]ResourceGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockResourceGroupsMockRecorder[ResourceGroup]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockResourceGroups[ResourceGroup])(nil).List), varargs...)
}

// ListPrismElements mocks base method.
func (m *MockResourceGroups[ResourceGroup]) ListPrismElements(ctx context.Context, resourceGroupUUID string) ([]converged.PrismElementInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrismElements", ctx, resourceGroupUUID)
	ret0, _ := ret[0].([]converged.PrismElementInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrismElements indicates an expected call of ListPrismElements.
func (mr *MockResourceGroupsMockRecorder[ResourceGroup]) ListPrismElements(ctx, resourceGroupUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrismElements", reflect.TypeOf((*MockResourceGroups[ResourceGroup])(nil).ListPrismElements), ctx, resourceGroupUUID)
}

// ListStorageContainers mocks base method.
func (m *MockResourceGroups[ResourceGroup]) ListStorageContainers(ctx context.Context, resourceGroupUUID string) ([]converged.StorageContainerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStorageContainers", ctx, resourceGroupUUID)
	ret0, _ := ret[0].([]converged.StorageContainerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStorageContainers indicates an expected call of ListStorageContainers.
func (mr *MockResourceGroupsMockRecorder[ResourceGroup]) ListStorageContainers(ctx, resourceGroupUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStorageContainers", reflect.TypeOf((*MockResourceGroups[ResourceGroup])(nil).ListStorageContainers), ctx, resourceGroupUUID)
}

// NewIterator mocks base method.
func (m *MockResourceGroups[ResourceGroup]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[ResourceGroup] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[ResourceGroup])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockResourceGroupsMockRecorder[ResourceGroup]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockResourceGroups[ResourceGroup])(nil).NewIterator), varargs...)
}
