// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: Users)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/users.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged Users
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockUsers is a mock of Users interface.
type MockUsers[User any] struct {
	ctrl     *gomock.Controller
	recorder *MockUsersMockRecorder[User]
	isgomock struct{}
}

// MockUsersMockRecorder is the mock recorder for MockUsers.
type MockUsersMockRecorder[User any] struct {
	mock *MockUsers[User]
}

// NewMockUsers creates a new mock instance.
func NewMockUsers[User any](ctrl *gomock.Controller) *MockUsers[User] {
	mock := &MockUsers[User]{ctrl: ctrl}
	mock.recorder = &MockUsersMockRecorder[User]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsers[User]) EXPECT() *MockUsersMockRecorder[User] {
	return m.recorder
}

// Get mocks base method.
func (m *MockUsers[User]) Get(ctx context.Context, uuid string) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUsersMockRecorder[User]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUsers[User])(nil).Get), ctx, uuid)
}

// List mocks base method.
func (m *MockUsers[User]) List(ctx context.Context, opts ...converged.ODataOption) ([]User, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUsersMockRecorder[User]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUsers[User])(nil).List), varargs...)
}

// NewIterator mocks base method.
func (m *MockUsers[User]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[User] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[User])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockUsersMockRecorder[User]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockUsers[User])(nil).NewIterator), varargs...)
}
