// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nutanix-cloud-native/prism-go-client/converged (interfaces: VMProfiles)
//
// Generated by this command:
//
//	mockgen -destination=mocks/converged/vm_profiles.go -package=mockconverged github.com/nutanix-cloud-native/prism-go-client/converged VMProfiles
//

// Package mockconverged is a generated GoMock package.
package mockconverged

import (
	context "context"
	reflect "reflect"

	converged "github.com/nutanix-cloud-native/prism-go-client/converged"
	gomock "go.uber.org/mock/gomock"
)

// MockVMProfiles is a mock of VMProfiles interface.
type MockVMProfiles[VMProfile any, VM any, DeployParams any] struct {
	ctrl     *gomock.Controller
	recorder *MockVMProfilesMockRecorder[VMProfile, VM, DeployParams]
	isgomock struct{}
}

// MockVMProfilesMockRecorder is the mock recorder for MockVMProfiles.
type MockVMProfilesMockRecorder[VMProfile any, VM any, DeployParams any] struct {
	mock *MockVMProfiles[VMProfile, VM, DeployParams]
}

// NewMockVMProfiles creates a new mock instance.
func NewMockVMProfiles[VMProfile any, VM any, DeployParams any](ctrl *gomock.Controller) *MockVMProfiles[VMProfile, VM, DeployParams] {
	mock := &MockVMProfiles[VMProfile, VM, DeployParams]{ctrl: ctrl}
	mock.recorder = &MockVMProfilesMockRecorder[VMProfile, VM, DeployParams]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVMProfiles[VMProfile, VM, DeployParams]) EXPECT() *MockVMProfilesMockRecorder[VMProfile, VM, DeployParams] {
	return m.recorder
}

// DeployVmWithVmProfile mocks base method.
func (m *MockVMProfiles[VMProfile, VM, DeployParams]) DeployVmWithVmProfile(ctx context.Context, vmProfileUUID string, params *DeployParams) (converged.Operation[VM], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeployVmWithVmProfile", ctx, vmProfileUUID, params)
	ret0, _ := ret[0].(converged.Operation[VM])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeployVmWithVmProfile indicates an expected call of DeployVmWithVmProfile.
func (mr *MockVMProfilesMockRecorder[VMProfile, VM, DeployParams]) DeployVmWithVmProfile(ctx, vmProfileUUID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeployVmWithVmProfile", reflect.TypeOf((*MockVMProfiles[VMProfile, VM, DeployParams])(nil).DeployVmWithVmProfile), ctx, vmProfileUUID, params)
}

// Get mocks base method.
func (m *MockVMProfiles[VMProfile, VM, DeployParams]) Get(ctx context.Context, uuid string) (*VMProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(*VMProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVMProfilesMockRecorder[VMProfile, VM, DeployParams]) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVMProfiles[VMProfile, VM, DeployParams])(nil).Get), ctx, uuid)
}

// List mocks base method.
func (m *MockVMProfiles[VMProfile, VM, DeployParams]) List(ctx context.Context, opts ...converged.ODataOption) ([]VMProfile, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]VMProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVMProfilesMockRecorder[VMProfile, VM, DeployParams]) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVMProfiles[VMProfile, VM, DeployParams])(nil).List), varargs...)
}

// NewIterator mocks base method.
func (m *MockVMProfiles[VMProfile, VM, DeployParams]) NewIterator(ctx context.Context, opts ...converged.ODataOption) converged.Iterator[VMProfile] {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewIterator", varargs...)
	ret0, _ := ret[0].(converged.Iterator[VMProfile])
	return ret0
}

// NewIterator indicates an expected call of NewIterator.
func (mr *MockVMProfilesMockRecorder[VMProfile, VM, DeployParams]) NewIterator(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIterator", reflect.TypeOf((*MockVMProfiles[VMProfile, VM, DeployParams])(nil).NewIterator), varargs...)
}
