apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../default

patches:
- target:
    kind: Secret
    name: 'nutanix-creds'
    namespace: capi-nutanix-system
  patch: |-
    - op: replace
      path: /stringData/credentials
      value: |
        [
          {
            "type": "basic_auth",
            "data": {
              "prismCentral":{
                "username": "${NUTANIX_USER}",
                "password": "${NUTANIX_PASSWORD}"
              },
              "prismElements": null
            }
          }
        ]
