name: Periodic Conformance Test with Calico
on:
  schedule:
    - cron: "0 6 * * *" # 6 AM
jobs:
  e2e:
    uses: ./.github/workflows/e2e.yaml
    with:
      e2e-labels: "conformance || cluster-upgrade-conformance"
      make-target: "test-e2e-calico"
    secrets: inherit
    permissions:
      contents: read
      checks: write
