name: Periodic Conformance Test with Cilium
on:
  schedule:
    - cron: "0 0 * * *" # Midnight
jobs:
  e2e:
    uses: ./.github/workflows/e2e.yaml
    with:
      e2e-labels: "conformance || cluster-upgrade-conformance"
      make-target: "test-e2e-cilium"
    secrets: inherit
    permissions:
      contents: read
      checks: write
