apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- behavior: merge
  files:
  - nutanix-csi-storage.yaml
  - nutanix-csi-snapshot.yaml
  - nutanix-csi-webhook.yaml
  name: nutanix-csi

resources:
- ../base/
- nutanix-csi.yaml
- nutanix-csi-crs.yaml

patches:
- path: csi-patch.yaml
