apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: nutanix-csi-crs
spec:
  clusterSelector:
    matchLabels:
      csi: nutanix
  resources:
  - kind: ConfigMap
    name: nutanix-csi
  strategy: ApplyOnce
